"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""                                                                                                                                                                                               
"                                                                                                                                                                                                                                                                         
"               ██╗   ██╗██╗███╗   ███╗██████╗  ██████╗                                                                                                                                                                                                                   
"               ██║   ██║██║████╗ ████║██╔══██╗██╔════╝                                                                                                                                                                                                                   
"               ██║   ██║██║██╔████╔██║██████╔╝██║                                                                                                                                                                                                                        
"               ╚██╗ ██╔╝██║██║╚██╔╝██║██╔══██╗██║                                                                                                                                                                                                                        
"                ╚████╔╝ ██║██║ ╚═╝ ██║██║  ██║╚██████╗                                                                                                                                                                                                                   
"                 ╚═══╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝                                                                                                                                                                                                                   
"                                                                                                                                                                                                                                                                         
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""                                                                                                                                                                                               
syntax on                                                                                                                                                                                                                                                                 
colorscheme molokai                                                                                                                                                                                                                                                       
nocompatible                                                                                                                                                                                                                                                          
set tabstop=4                                                                                                                                                                                                                                                             
set shiftwidth=2                                                                                                                                                                                                                                                          
set expandtab                                                                                                                                                                                                                                                             
set ai                                                                                                                                                                                                                                                                    
set number                                                                                                                                                                                                                                                                
set hlsearch                                                                                                                                                                                                                                                              
set ruler                                                                                                                                                                                                                                                                 
set incsearch                                                                                                                                                                                                                                                             
set wildmenu                                                                                                                                                                                                                                                              
set wildmode=list:longest                                                                                                                                                                                                                                                 
set background=dark                                                                                                                                                                                                                                                       
filetype on                                                                                                                                                                                                                                                               
highlight Comment ctermfg=green 
